twig:
    file_name_pattern: '*.twig'
    form_themes:
        - 'bootstrap_5_layout.html.twig'
        - 'form/captcha.html.twig'
        - 'form/repeated_password.html.twig'

when@test:
    twig:
        strict_variables: true
